import { ShaderLabComposition } from '@basementstudio/shader-lab';

/** Shader Lab export — animated gradient + optional stacked effects (off by default) */
const homeShaderConfig = {
  layers: [
    {
      blendMode: 'normal',
      compositeMode: 'filter',
      maskConfig: {
        invert: false,
        mode: 'multiply',
        source: 'luminance',
      },
      hue: 0,
      id: '8f621e7b-a310-46d7-a2ed-6c015473d2bc',
      kind: 'effect',
      name: 'CRT',
      opacity: 1,
      params: {
        crtMode: 'slot-mask',
        cellSize: 6,
        scanlineIntensity: 0.17,
        maskIntensity: 0.27,
        barrelDistortion: 0.031,
        chromaticAberration: 1.59,
        beamFocus: 0.58,
        brightness: 1.2,
        highlightDrive: 1,
        highlightThreshold: 0.62,
        shoulder: 0.25,
        chromaRetention: 1.15,
        shadowLift: 0.16,
        persistence: 0.18,
        vignetteIntensity: 0,
        flickerIntensity: 0.05,
        glitchIntensity: 0.13,
        glitchSpeed: 1.7,
        signalArtifacts: 0.45,
        bloomEnabled: true,
        bloomIntensity: 1.63,
        bloomThreshold: 0,
        bloomRadius: 24,
        bloomSoftness: 0.18,
      },
      saturation: 1,
      type: 'crt',
      visible: false,
    },
    {
      blendMode: 'lighten',
      compositeMode: 'filter',
      maskConfig: {
        invert: false,
        mode: 'multiply',
        source: 'luminance',
      },
      hue: 22,
      id: '6bfa2084-cf57-4f8a-bb49-57cfa1c74b1c',
      kind: 'effect',
      name: 'Dithering',
      opacity: 0.74,
      params: {
        preset: 'custom',
        algorithm: 'bayer-2x2',
        colorMode: 'source',
        monoColor: '#f5f5f0',
        shadowColor: '#101010',
        highlightColor: '#f5f2e8',
        pixelSize: 1,
        spread: 0.66,
        levels: 13,
        dotScale: 0.1,
        animateDither: false,
        ditherSpeed: 0.5,
        chromaticSplit: false,
      },
      saturation: 1.7,
      type: 'dithering',
      visible: false,
    },
    {
      blendMode: 'normal',
      compositeMode: 'mask',
      maskConfig: {
        invert: false,
        mode: 'multiply',
        source: 'luminance',
      },
      hue: 0,
      id: '0e3136ed-a783-4527-888d-269caeb49a9f',
      kind: 'source',
      name: 'Text',
      opacity: 1,
      params: {
        text: 'basement',
        anchor: 'center',
        offset: [0, 0],
        fontSize: 201,
        fontFamily: 'sans',
        fontWeight: 800,
        letterSpacing: -0.1,
        textColor: '#ffffff',
        backgroundColor: '#000000',
        backgroundAlpha: 1,
      },
      saturation: 1,
      type: 'text',
      visible: false,
    },
    {
      blendMode: 'lighten',
      compositeMode: 'filter',
      maskConfig: {
        invert: false,
        mode: 'multiply',
        source: 'luminance',
      },
      hue: 2,
      id: '99109d60-a6ce-44a8-9832-24905d6c14bb',
      kind: 'effect',
      name: 'Pattern',
      opacity: 1,
      params: {
        cellSize: 6,
        preset: 'shapes',
        colorMode: 'monochrome',
        monoColor: '#FFB2DF',
        bgOpacity: 0.16,
        invert: false,
        customColorCount: 4,
        customLuminanceBias: 0,
        customBgColor: '#F5F5F0',
        customColor1: '#0d1014',
        customColor2: '#4d5057',
        customColor3: '#969aa2',
        customColor4: '#e1e2de',
        bloomEnabled: true,
        bloomIntensity: 8,
        bloomThreshold: 0.14,
        bloomRadius: 10.75,
        bloomSoftness: 0.8,
      },
      saturation: 1.63,
      type: 'pattern',
      visible: false,
    },
    {
      blendMode: 'normal',
      compositeMode: 'filter',
      maskConfig: {
        invert: false,
        mode: 'multiply',
        source: 'luminance',
      },
      hue: -20,
      id: 'a924d323-7026-4b54-8738-355ef0d17009',
      kind: 'source',
      name: 'Gradient',
      opacity: 1,
      params: {
        preset: 'deep-ocean',
        activePoints: 4,
        point1Color: '#FF9E9E',
        point1Position: [-0.76, -0.33],
        point1Weight: 1.14,
        point2Color: '#F72A66',
        point2Position: [-0.26, -0.15],
        point2Weight: 1.86,
        point3Color: '#FF3232',
        point3Position: [0.87, 0.31],
        point3Weight: 1.75,
        point4Color: '#93B837',
        point4Position: [-1.06, -0.73],
        point4Weight: 0.65,
        point5Color: '#1a0a2e',
        point5Position: [-0.5, 0.7],
        point5Weight: 1,
        noiseType: 'voronoi',
        noiseSeed: 81.3,
        warpAmount: 0.49,
        warpScale: 2.03,
        warpIterations: 3,
        warpDecay: 1.22,
        warpBias: 0.4,
        vortexAmount: -0.01,
        animate: true,
        motionAmount: 0.74,
        motionSpeed: 0.84,
        falloff: 2.02,
        tonemapMode: 'totos',
        glowStrength: 0,
        glowThreshold: 0,
        grainAmount: 0,
        vignetteStrength: 0,
        vignetteRadius: 1.3,
        vignetteSoftness: 0.7,
      },
      saturation: 1.15,
      type: 'gradient',
      visible: true,
    },
  ],
  timeline: {
    duration: 8,
    loop: true,
    tracks: [],
  },
};

export function ExportedShader() {
  return (
    <ShaderLabComposition
      className="home-shader-bg"
      config={homeShaderConfig}
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 0,
        pointerEvents: 'none',
        width: '100%',
        height: '100%',
      }}
    />
  );
}

export default ExportedShader;
